### ISSUE TITLE
Themes?

### ISSUE THREAD

**Issue by tohuw** [octopress/codefence#10]
Your examples show some themes, which are really nice-looking.

How do we invoke those, or do you have the appropriate stylesheets for those somewhere?

**Comment by imathis** [comment]
Right now [octopress-solarized](https://github.com/octopress/solarized) has the solarized theme. I'm thinking of building a code-themes gem that includes several themes and lets you switch between then by configuration.

**Comment by tohuw** [comment]
Great, thanks!

**Comment by tohuw** [comment]
Sorry, one other small question: how do you use the light theme vs. the dark one?

**Comment by imathis** [comment]
Run: `octopress ink copy solarized --config` which will install the configuration for that plugin. Then change `style: dark` to `style: light`.
