### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by hseeberger** [octopress/codefence#11]
I have just installed Jekyll 3, the latest octopress, octopress-genesis-theme and octopress-codefence, but there's no code highlighting. I'm using a Mac with
```
hseeberger.github.io$ ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
hseeberger.github.io$ python --version
Python 2.7.6
```

**Comment by imathis** [comment]
Do you mean that the code isn't being stylized or that the output ins't being converted properly? Just so you know, this plugin does not contain a stylesheets, you'll need to install [octopress-solarized](https://github.com/octopress/solarized) or roll your own styles.

**Comment by hseeberger** [comment]
Ah, that information helps ;-)
