### ISSUE TITLE
Usage instructions incorrect?

### ISSUE THREAD

**Issue by IanWhitney** [octopress/codefence#5]
Using Octopress 3.0.0.rc.23 and the current master of Codefence.

Putting `{% css_asset_tag %}` in the head.html include only led to errors

```
Liquid Exception: Unknown tag 'css_asset_tag' in _includes/head.html, included in _layouts/default.html
```

**Comment by imathis** [comment]
I've just released a fix for this. You should be able to `bundle update` and all should work. Thanks for the help!
